import{useEffect,useState}from'react'
import{useTranslation}from'react-i18next'
import Icon,{type IconName}from'../../components/Icon'
import{formatDate,formatNumber,normalizeLocale}from'../../i18n'
import{workspaceApi}from'../../workspace/api'
import type{WorkspaceQuota,WorkspaceQuotaItem}from'../../workspace/types'
import type{Locale}from'../../types'

const ICONS:Record<string,IconName>={storage_bytes:'database',resources:'folder',max_steps_per_resource:'list',members:'users',active_shares:'share',monthly_ai_tokens:'ai',monthly_exports:'download',monthly_video_minutes:'play',monthly_public_views:'eye',monthly_download_bytes:'download'}
function display(item:WorkspaceQuotaItem,locale:Locale){if(item.key.includes('bytes')){const units=['B','KB','MB','GB','TB'];const fmt=(v:number)=>{const i=v?Math.min(Math.floor(Math.log(v)/Math.log(1024)),4):0;return`${new Intl.NumberFormat(locale,{maximumFractionDigits:1}).format(v/1024**i)} ${units[i]}`};return`${fmt(item.used)} / ${fmt(item.limit||0)}`}return`${formatNumber(item.used,locale)} / ${item.limit==null?'∞':formatNumber(item.limit,locale)}`}
export default function WorkspaceQuotas(){const{t,i18n}=useTranslation(['workspace','common']),locale=normalizeLocale(i18n.language),[value,setValue]=useState<WorkspaceQuota|null>(null),[error,setError]=useState('');useEffect(()=>{workspaceApi.quotas().then(setValue).catch(e=>setError(e.message))},[]);return <main className="workspace-page workspace-quotas"><header className="workspace-page-heading"><div><h1>{t('quotas.title')}</h1><p>{t('quotas.subtitle')}</p></div>{value&&<span className="quota-plan-badge"><Icon name="shield"/>{value.plan.name}</span>}</header>{error?<div className="workspace-state error">{error}</div>:!value?<div className="workspace-state">{t('loading')}</div>:<><section className="quota-summary"><div><small>{t('quotas.currentPlan')}</small><strong>{value.plan.name}</strong><p>{value.plan.description||t('quotas.defaultDescription')}</p></div><div><small>{t('quotas.reset')}</small><strong>{formatDate(value.period.resets_at,locale)}</strong><p>{t(value.has_overrides?'quotas.overridden':'quotas.standard')}</p></div></section><section className="quota-grid">{value.items.map(item=><article className={item.status} key={item.key}><header><span><Icon name={ICONS[item.key]||'analytics'}/></span><div><strong>{t(`quotas.metrics.${item.key}`)}</strong><small>{t(`quotas.${item.enforcement}`)}</small></div><b>{Math.min(999,item.percent)}%</b></header><div className="quota-progress"><i style={{width:`${Math.min(100,item.percent)}%`}}/></div><footer><strong>{display(item,locale)}</strong><small>{item.status==='exceeded'?t('quotas.exceeded'):item.status==='warning'?t('quotas.warning'):t('quotas.available')}</small></footer></article>)}</section><section className="workspace-panel quota-note"><Icon name="help"/><div><strong>{t('quotas.noteTitle')}</strong><p>{t('quotas.note')}</p></div></section></>}</main>}
