import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import type { NotificationChannel, NotificationChannelInput } from '../../monitoring/types'

export default function ChannelDialog({ channel, busy, onClose, onSave }: { channel?:NotificationChannel|null; busy:boolean; onClose:()=>void; onSave:(value:NotificationChannelInput)=>void }) {
  const {t}=useTranslation(['monitoring','common'])
  const [value,setValue]=useState<NotificationChannelInput>({name:channel?.name||'',kind:channel?.kind||'webhook',target:'',minimum_severity:channel?.minimum_severity||'warning',enabled:channel?.enabled??true})
  return <div className="monitor-dialog-layer" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><form className="monitor-dialog" onSubmit={event=>{event.preventDefault();onSave(value)}}><header><div><h2>{t(channel?'channels.edit':'channels.create')}</h2><p>{t('channels.formHint')}</p></div><button type="button" onClick={onClose}>×</button></header><div className="monitor-form"><label>{t('channels.fields.name')}<input required value={value.name} onChange={event=>setValue({...value,name:event.target.value})}/></label><label>{t('channels.fields.kind')}<select disabled={!!channel} value={value.kind} onChange={event=>setValue({...value,kind:event.target.value as NotificationChannelInput['kind']})}><option value="webhook">Webhook</option><option value="email">Email</option></select></label><label className="wide">{t('channels.fields.target')}<input required={!channel} type={value.kind==='email'?'email':'url'} value={value.target} placeholder={channel?channel.target_masked:value.kind==='email'?'ops@example.com':'https://hooks.example.com/...'} onChange={event=>setValue({...value,target:event.target.value})}/><small>{channel?t('channels.targetRetained'):t(`channels.targetHint.${value.kind}`)}</small></label><label>{t('channels.fields.minimum')}<select value={value.minimum_severity} onChange={event=>setValue({...value,minimum_severity:event.target.value as NotificationChannelInput['minimum_severity']})}><option value="critical">{t('severity.critical')}</option><option value="warning">{t('severity.warning')}</option><option value="info">{t('severity.info')}</option></select></label><label className="monitor-check"><input type="checkbox" checked={value.enabled} onChange={event=>setValue({...value,enabled:event.target.checked})}/>{t('channels.fields.enabled')}</label></div><footer><button type="button" onClick={onClose}>{t('common:actions.cancel')}</button><button className="primary" disabled={busy}>{t(busy?'saving':'common:actions.save')}</button></footer></form></div>
}
