import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import type { AlertRule, AlertRuleInput, MetricDefinition } from '../../monitoring/types'

const EMPTY: AlertRuleInput = { name:'', metric_key:'api.error_rate_5m', operator:'gte', threshold:5, severity:'warning', consecutive_periods:2, cooldown_minutes:15, enabled:true }

export default function RuleDialog({ rule, metrics, busy, onClose, onSave }: { rule?: AlertRule | null; metrics: MetricDefinition[]; busy:boolean; onClose:()=>void; onSave:(value:AlertRuleInput)=>void }) {
  const {t}=useTranslation(['monitoring','common'])
  const [value,setValue]=useState<AlertRuleInput>(rule?{name:rule.name,metric_key:rule.metric_key,operator:rule.operator,threshold:rule.threshold,severity:rule.severity,consecutive_periods:rule.consecutive_periods,cooldown_minutes:rule.cooldown_minutes,enabled:rule.enabled}:EMPTY)
  function selectMetric(key:string){const metric=metrics.find(item=>item.key===key);setValue(current=>({...current,metric_key:key,operator:(metric?.recommended_operator as AlertRuleInput['operator'])||current.operator,threshold:metric?.recommended_threshold??current.threshold}))}
  return <div className="monitor-dialog-layer" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><form className="monitor-dialog" onSubmit={event=>{event.preventDefault();onSave(value)}}><header><div><h2>{t(rule?'rules.edit':'rules.create')}</h2><p>{t('rules.formHint')}</p></div><button type="button" onClick={onClose}>×</button></header><div className="monitor-form"><label className="wide">{t('rules.fields.name')}<input required maxLength={160} value={value.name} onChange={event=>setValue({...value,name:event.target.value})}/></label><label className="wide">{t('rules.fields.metric')}<select disabled={!!rule} value={value.metric_key} onChange={event=>selectMetric(event.target.value)}>{metrics.map(item=><option key={item.key} value={item.key}>{t(`metrics.catalog.${item.key}`,{defaultValue:item.key})}</option>)}</select></label><label>{t('rules.fields.operator')}<select value={value.operator} onChange={event=>setValue({...value,operator:event.target.value as AlertRuleInput['operator']})}>{['gt','gte','lt','lte','eq'].map(item=><option key={item} value={item}>{t(`operators.${item}`)}</option>)}</select></label><label>{t('rules.fields.threshold')}<input type="number" step="any" required value={value.threshold} onChange={event=>setValue({...value,threshold:Number(event.target.value)})}/></label><label>{t('rules.fields.severity')}<select value={value.severity} onChange={event=>setValue({...value,severity:event.target.value as AlertRuleInput['severity']})}><option value="critical">{t('severity.critical')}</option><option value="warning">{t('severity.warning')}</option><option value="info">{t('severity.info')}</option></select></label><label>{t('rules.fields.periods')}<input type="number" min="1" max="60" value={value.consecutive_periods} onChange={event=>setValue({...value,consecutive_periods:Number(event.target.value)})}/></label><label>{t('rules.fields.cooldown')}<input type="number" min="1" max="1440" value={value.cooldown_minutes} onChange={event=>setValue({...value,cooldown_minutes:Number(event.target.value)})}/></label><label className="monitor-check wide"><input type="checkbox" checked={value.enabled} onChange={event=>setValue({...value,enabled:event.target.checked})}/>{t('rules.fields.enabled')}</label></div><footer><button type="button" onClick={onClose}>{t('common:actions.cancel')}</button><button className="primary" disabled={busy}>{t(busy?'saving':'common:actions.save')}</button></footer></form></div>
}
