import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { normalizeLocale } from '../../i18n'
import { formatQuotaValue, quotaMetric } from '../../quota/catalog'
import type { QuotaSpace } from '../../quota/types'
import Icon from '../Icon'
import QuotaSpaceDrawer from './QuotaSpaceDrawer'

export default function QuotaSpacesPanel({ spaces }: { spaces: QuotaSpace[] }) {
  const { t, i18n } = useTranslation(['admin', 'platformSettings'])
  const locale = normalizeLocale(i18n.language)
  const [query, setQuery] = useState(''), [kind, setKind] = useState(''), [health, setHealth] = useState(''), [selected, setSelected] = useState<QuotaSpace | null>(null)
  const filtered = useMemo(() => spaces.filter(item => (!kind || item.kind === kind) && (!health || item.health === health) && (!query.trim() || `${item.name} ${item.owner_name} ${item.owner_email} ${item.plan.name}`.toLowerCase().includes(query.trim().toLowerCase()))), [spaces, query, kind, health])
  return <section className="quota-space-list"><header><div><strong>{t('admin:quotas.spaces.title')}</strong><small>{t('admin:quotas.spaces.count', { count: filtered.length })}</small></div><div><label className="admin-search"><Icon name="search" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder={t('admin:quotas.spaces.search')} /></label><select value={kind} onChange={event => setKind(event.target.value)}><option value="">{t('admin:quotas.types.all')}</option><option value="team">{t('admin:quotas.types.team')}</option><option value="personal">{t('admin:quotas.types.personal')}</option></select><select value={health} onChange={event => setHealth(event.target.value)}><option value="">{t('admin:quotas.health.all')}</option><option value="normal">{t('admin:quotas.health.normal')}</option><option value="warning">{t('admin:quotas.health.warning')}</option><option value="exceeded">{t('admin:quotas.health.exceeded')}</option></select></div></header><div className="quota-space-table-wrap"><table><thead><tr><th>{t('admin:quotas.spaces.columns.space')}</th><th>{t('admin:quotas.spaces.columns.plan')}</th><th>{t('admin:quotas.spaces.columns.highest')}</th><th>{t('admin:quotas.spaces.columns.status')}</th><th>{t('admin:quotas.spaces.columns.growth')}</th><th /></tr></thead><tbody>{filtered.map(space => { const highest = space.items.find(item => item.key === space.highest_metric), catalog = quotaMetric(space.highest_metric); return <tr key={space.id} className={selected?.id === space.id ? 'selected' : ''} onClick={() => setSelected(space)}><td><div className="quota-space-name"><span><Icon name={space.kind === 'personal' ? 'user' : 'users'} /></span><div><strong>{space.name}</strong><small>{space.owner_name || space.owner_email} · {t(`admin:quotas.types.${space.kind}`)}</small></div></div></td><td><strong>{space.plan.name}</strong>{space.has_overrides && <small>{t('admin:quotas.overrides')}</small>}</td><td><div className="quota-highest"><span className={`quota-metric-icon ${catalog.tone}`}><Icon name={catalog.icon} /></span><div><strong>{t(`platformSettings:quota.metrics.${space.highest_metric}`)}</strong><small>{formatQuotaValue(space.highest_metric, highest?.used, locale)} / {formatQuotaValue(space.highest_metric, highest?.limit, locale)}</small></div><b>{highest?.percent.toFixed(1)}%</b></div></td><td><span className={`quota-health ${space.health}`}><i />{t(`admin:quotas.health.${space.health}`)}</span></td><td><strong className={space.growth_percent > 0 ? 'quota-growth-up' : ''}>{space.growth_percent > 0 ? '+' : ''}{space.growth_percent}%</strong></td><td><Icon name="chevronRight" /></td></tr> })}</tbody></table>{!filtered.length && <div className="quota-empty"><Icon name="database" />{t('admin:quotas.spaces.empty')}</div>}</div>{selected && <QuotaSpaceDrawer space={selected} onClose={() => setSelected(null)} />}</section>
}
