import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import ChannelDialog from '../../components/monitoring/ChannelDialog'
import MonitoringNav from '../../components/monitoring/MonitoringNav'
import SeverityBadge from '../../components/monitoring/SeverityBadge'
import Icon from '../../components/Icon'
import { useToast } from '../../components/toast'
import { formatDate, normalizeLocale } from '../../i18n'
import { monitoringApi } from '../../monitoring/api'
import type { NotificationChannel, NotificationChannelInput } from '../../monitoring/types'

export default function NotificationChannels(){
  const {t,i18n}=useTranslation(['monitoring','common']),locale=normalizeLocale(i18n.language),toast=useToast();const [items,setItems]=useState<NotificationChannel[]>([]),[editing,setEditing]=useState<NotificationChannel|null|undefined>(undefined),[busy,setBusy]=useState(false),[testing,setTesting]=useState(''),[error,setError]=useState('')
  const load=()=>monitoringApi.channels().then(setItems).catch(reason=>setError(reason.message));useEffect(()=>{load()},[])
  async function save(value:NotificationChannelInput){setBusy(true);try{if(editing){const patch={...value,...(!value.target?{target:undefined}:{})};await monitoringApi.updateChannel(editing.id,patch)}else await monitoringApi.createChannel(value);setEditing(undefined);toast.success(t('channels.saved'));await load()}catch(reason){toast.error((reason as Error).message)}finally{setBusy(false)}}
  async function test(item:NotificationChannel){setTesting(item.id);try{const result=await monitoringApi.testChannel(item.id);result.last_status==='success'?toast.success(t('channels.testSuccess')):toast.error(result.last_error||t('channels.testFailed'));await load()}catch(reason){toast.error((reason as Error).message)}finally{setTesting('')}}
  async function remove(item:NotificationChannel){if(!confirm(t('channels.deleteConfirm',{name:item.name})))return;try{await monitoringApi.deleteChannel(item.id);toast.success(t('channels.deleted'));await load()}catch(reason){toast.error((reason as Error).message)}}
  return <main className="admin-content-page monitoring-page"><div className="admin-page-intro"><div><h1>{t('channels.title')}</h1><p>{t('channels.subtitle')}</p></div><button className="primary icon-button" onClick={()=>setEditing(null)}><Icon name="plus"/>{t('channels.create')}</button></div><MonitoringNav/>{error&&<div className="error">{error}</div>}<div className="monitor-channel-grid">{items.map(item=><article key={item.id}><header><span><Icon name={item.kind==='webhook'?'link':'message'}/></span><div><strong>{item.name}</strong><small>{item.kind.toUpperCase()}</small></div><button className={`model-toggle ${item.enabled?'active':''}`} onClick={async()=>{await monitoringApi.updateChannel(item.id,{enabled:!item.enabled});await load()}}><i/></button></header><div><label>{t('channels.destination')}</label><code>{item.target_masked}</code><label>{t('channels.minimum')}</label><SeverityBadge value={item.minimum_severity}/><label>{t('channels.lastDelivery')}</label><span className={`monitor-delivery ${item.last_status}`}>{t(`channels.status.${item.last_status}`,{defaultValue:item.last_status})}{item.last_sent_at&&<small>{formatDate(item.last_sent_at,locale)}</small>}</span>{item.last_error&&<p>{item.last_error}</p>}</div><footer><button disabled={testing===item.id} onClick={()=>test(item)}>{testing===item.id?<span className="action-spinner"/>:<Icon name="link"/>}{t('channels.test')}</button><button onClick={()=>setEditing(item)}><Icon name="edit"/>{t('common:actions.edit')}</button><button className="danger" onClick={()=>remove(item)}><Icon name="delete"/></button></footer></article>)}{!items.length&&<div className="monitor-empty monitor-channel-empty"><Icon name="message" size={32}/><strong>{t('channels.empty')}</strong><p>{t('channels.emptyHint')}</p></div>}</div>{editing!==undefined&&<ChannelDialog channel={editing} busy={busy} onClose={()=>setEditing(undefined)} onSave={save}/>}</main>
}
