import { useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { api } from '../api'
import AdminPagination from '../components/AdminPagination'
import Icon from '../components/Icon'
import { formatDate, formatNumber, normalizeLocale } from '../i18n'
import type { AdminOrganization, AdminUser, AIModelConfig, AIUsagePoint, AIUsageRecord, AIUsageSummary } from '../types'

const point = { key: 'total', label: '', requests: 0, input_tokens: 0, output_tokens: 0, total_tokens: 0, avg_latency_ms: 0 }
const emptySummary: AIUsageSummary = { totals: point, trend: [], by_user: [], by_organization: [], by_model: [], by_resource: [], by_status: [], by_operation: [] }
type Series = { key: keyof AIUsagePoint; label: string; color: string }

function InteractiveLineChart({ points = [], series }: { points?: AIUsagePoint[]; series: Series[] }) {
  const [hover, setHover] = useState<number | null>(null), width = 900, height = 240, pad = 30
  const max = Math.max(1, ...points.flatMap(item => series.map(value => Number(item[value.key]) || 0)))
  const xy = (item: AIUsagePoint, index: number, value: Series) => ({ x: pad + index * (width-pad*2)/Math.max(1, points.length-1), y: height-pad-(Number(item[value.key]) || 0)/max*(height-pad*2) })
  return <div className="interactive-line-chart"><svg viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none">
    {[0,.25,.5,.75,1].map(line => <line className="chart-grid-line" key={line} x1={pad} x2={width-pad} y1={pad+line*(height-pad*2)} y2={pad+line*(height-pad*2)} />)}
    {series.map(value => <polyline key={value.label} points={points.map((item,index) => { const p=xy(item,index,value); return `${p.x},${p.y}` }).join(' ')} fill="none" stroke={value.color} strokeWidth="3" vectorEffect="non-scaling-stroke" />)}
    {points.map((item,index) => { const x=pad+index*(width-pad*2)/Math.max(1,points.length-1); return <rect key={item.key} x={x-Math.max(5,(width-pad*2)/Math.max(1,points.length)/2)} y={0} width={Math.max(10,(width-pad*2)/Math.max(1,points.length))} height={height} fill="transparent" onMouseEnter={()=>setHover(index)} onMouseLeave={()=>setHover(null)} /> })}
    {hover !== null && points[hover] && series.map(value => { const p=xy(points[hover],hover,value); return <circle key={value.label} cx={p.x} cy={p.y} r="6" fill="#fff" stroke={value.color} strokeWidth="3" /> })}
  </svg>{hover !== null && points[hover] && <div className="chart-tooltip usage-tooltip" style={{ left: `${Math.min(88, Math.max(12, hover/Math.max(1,points.length-1)*100))}%` }}><strong>{points[hover].label}</strong>{series.map(value => <span key={value.label}><i style={{background:value.color}} />{value.label}<b>{Number(points[hover][value.key] || 0).toLocaleString()}</b></span>)}</div>}<div className="chart-axis"><span>{points[0]?.label || '—'}</span><span>{points.at(-1)?.label || '—'}</span></div><div className="chart-legend">{series.map(value => <span key={value.label}><i style={{background:value.color}} />{value.label}</span>)}</div></div>
}

function VerticalBars({ title, items = [], onSelect }: { title: string; items?: AIUsagePoint[]; onSelect?: (item: AIUsagePoint) => void }) {
  const max = Math.max(1, ...items.map(item => item.total_tokens)), visible = items.slice(0, 10)
  return <section className="usage-bars-card"><header><strong>{title}</strong><small>{items.length}</small></header><div className="vertical-bars">{visible.map((item,index) => <button key={item.key} onClick={() => onSelect?.(item)} title={`${item.label}: ${item.total_tokens}`}><span><em style={{height:`${Math.max(3,item.total_tokens/max*100)}%`}} className={`tone-${index%5}`} /><b>{item.total_tokens.toLocaleString()}</b></span><small>{item.label}</small></button>)}{!visible.length && <p>—</p>}</div></section>
}

function StatusDonut({ items = [], title }: { items?: AIUsagePoint[]; title: string }) {
  const success = items.find(item => item.key === 'success')?.requests || 0, failed = items.find(item => item.key === 'failed')?.requests || 0, total = Math.max(1, success + failed), angle = success/total*360
  return <section className="usage-donut-card"><header><strong>{title}</strong></header><div><div className="usage-donut" style={{background:`conic-gradient(#22a660 0 ${angle}deg,#e05260 ${angle}deg 360deg)`}}><span><b>{success+failed}</b><small>requests</small></span></div><ul><li><i className="success"/><span>Success</span><b>{success}</b></li><li><i className="failed"/><span>Failed</span><b>{failed}</b></li></ul></div></section>
}

export default function AdminAIUsage() {
  const { t, i18n } = useTranslation(['admin', 'common']); const locale = normalizeLocale(i18n.language)
  const [summary,setSummary]=useState(emptySummary), [records,setRecords]=useState<AIUsageRecord[]>([]), [models,setModels]=useState<AIModelConfig[]>([]), [users,setUsers]=useState<AdminUser[]>([]), [organizations,setOrganizations]=useState<AdminOrganization[]>([])
  const [days,setDays]=useState(30), [modelId,setModelId]=useState(''), [userId,setUserId]=useState(''), [organizationId,setOrganizationId]=useState(''), [status,setStatus]=useState(''), [query,setQuery]=useState(''), [page,setPage]=useState(1), [pageSize,setPageSize]=useState(10), [total,setTotal]=useState(0), [loading,setLoading]=useState(true), [error,setError]=useState('')
  useEffect(()=>{ Promise.all([api.aiModels(),api.adminUsers({page_size:100}),api.adminOrganizations()]).then(([m,u,o])=>{setModels(m);setUsers(u.items);setOrganizations(o)}).catch(()=>undefined)},[])
  useEffect(()=>{setLoading(true);setError('');Promise.all([api.aiUsageSummary({days,model_id:modelId,user_id:userId,organization_id:organizationId}),api.aiUsageRequests({query,model_id:modelId,user_id:userId,organization_id:organizationId,status,page,page_size:pageSize})]).then(([s,r])=>{setSummary({
    ...emptySummary,
    ...s,
    totals: { ...point, ...s.totals },
    trend: Array.isArray(s.trend) ? s.trend : [],
    by_user: Array.isArray(s.by_user) ? s.by_user : [],
    by_organization: Array.isArray(s.by_organization) ? s.by_organization : [],
    by_model: Array.isArray(s.by_model) ? s.by_model : [],
    by_resource: Array.isArray(s.by_resource) ? s.by_resource : [],
    by_status: Array.isArray(s.by_status) ? s.by_status : [],
    by_operation: Array.isArray(s.by_operation) ? s.by_operation : [],
  });setRecords(Array.isArray(r.items) ? r.items : []);setTotal(r.total || 0)}).catch(value=>setError(value.message)).finally(()=>setLoading(false))},[days,modelId,userId,organizationId,status,query,page,pageSize])
  const metrics=useMemo(()=>[{icon:'database' as const,label:t('usage.metrics.tokens'),value:summary.totals.total_tokens},{icon:'text' as const,label:t('usage.metrics.input'),value:summary.totals.input_tokens},{icon:'ai' as const,label:t('usage.metrics.output'),value:summary.totals.output_tokens},{icon:'clock' as const,label:t('usage.metrics.firstToken'),value:summary.totals.avg_first_token_ms,suffix:' ms'},{icon:'analytics' as const,label:t('usage.metrics.latency'),value:summary.totals.avg_latency_ms,suffix:' ms'}],[summary,t])
  const reset=(setter:(value:string)=>void,value:string)=>{setter(value);setPage(1)}
  return <div className="admin-content-page ai-usage-page"><div className="admin-page-intro"><div><h1>{t('usage.title')}</h1><p>{t('usage.subtitle')}</p></div><span>{t('usage.requests',{count:summary.totals.requests})}</span></div>
    <div className="usage-filters"><select value={days} onChange={event=>setDays(Number(event.target.value))}>{[7,30,90,365].map(value=><option value={value} key={value}>{t('usage.days',{count:value})}</option>)}</select><select value={modelId} onChange={event=>reset(setModelId,event.target.value)}><option value="">{t('usage.allModels')}</option>{models.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><select value={organizationId} onChange={event=>reset(setOrganizationId,event.target.value)}><option value="">{t('usage.allTeams')}</option>{organizations.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><select value={userId} onChange={event=>reset(setUserId,event.target.value)}><option value="">{t('usage.allUsers')}</option>{users.map(item=><option value={item.id} key={item.id}>{item.name||item.email}</option>)}</select></div>{error&&<div className="error">{error}</div>}
    <div className="usage-metrics">{metrics.map(item=><article key={item.label}><span><Icon name={item.icon}/></span><div><small>{item.label}</small><strong>{item.value==null?'—':`${formatNumber(item.value,locale)}${item.suffix||''}`}</strong></div></article>)}</div>
    <div className="usage-line-grid"><section className="usage-chart-card"><header><div><strong>{t('usage.trend')}</strong><small>{t('usage.trendHint')}</small></div></header><InteractiveLineChart points={summary.trend} series={[{key:'input_tokens',label:t('usage.metrics.input'),color:'#635bff'},{key:'output_tokens',label:t('usage.metrics.output'),color:'#22a660'}]}/></section><section className="usage-chart-card"><header><div><strong>{t('usage.performance')}</strong><small>{t('usage.performanceHint')}</small></div></header><InteractiveLineChart points={summary.trend} series={[{key:'avg_latency_ms',label:t('usage.metrics.latency'),color:'#ef8b3b'},{key:'avg_first_token_ms',label:t('usage.metrics.firstToken'),color:'#e05294'}]}/></section></div>
    <div className="usage-visual-grid"><VerticalBars title={t('usage.byTeam')} items={summary.by_organization} onSelect={item=>reset(setOrganizationId,item.key==='unknown'?'':item.key)}/><VerticalBars title={t('usage.byUser')} items={summary.by_user} onSelect={item=>reset(setUserId,item.key==='unknown'?'':item.key)}/><VerticalBars title={t('usage.byModel')} items={summary.by_model} onSelect={item=>reset(setModelId,item.key==='unknown'?'':item.key)}/><VerticalBars title={t('usage.byResource')} items={summary.by_resource}/><VerticalBars title={t('usage.byOperation')} items={summary.by_operation}/><StatusDonut title={t('usage.statusDistribution')} items={summary.by_status}/></div>
    <section className="admin-list-card usage-detail-card"><header><div><strong>{t('usage.details')}</strong><small>{t('usage.detailsHint')}</small></div><div><label className="admin-search"><Icon name="search"/><input value={query} onChange={event=>reset(setQuery,event.target.value)} placeholder={t('usage.search')}/></label><select value={status} onChange={event=>reset(setStatus,event.target.value)}><option value="">{t('usage.allStatuses')}</option><option value="success">{t('usage.success')}</option><option value="failed">{t('usage.failed')}</option></select></div></header><div className="usage-table-wrap"><table className="usage-table"><thead><tr><th>{t('usage.columns.time')}</th><th>{t('usage.columns.resource')}</th><th>{t('usage.columns.userTeam')}</th><th>{t('usage.columns.model')}</th><th>{t('usage.columns.tokens')}</th><th>{t('usage.columns.firstToken')}</th><th>{t('usage.columns.latency')}</th><th>{t('usage.columns.status')}</th></tr></thead><tbody>{records.map(item=><tr key={item.id}><td><time>{formatDate(item.created_at,locale)}</time><small>{item.operation}</small></td><td><strong>{item.demo_title||'—'}</strong><details><summary>{t('usage.requestDetail')}</summary><pre>{JSON.stringify({request_id:item.request_id,request:item.request_detail,response:item.response_detail,error:item.error||undefined},null,2)}</pre></details></td><td><strong>{item.user_name||item.user_email||'—'}</strong><small>{item.organization_name||'—'}</small></td><td>{item.model_name}</td><td><strong>{formatNumber(item.total_tokens,locale)}</strong><small>↑ {formatNumber(item.input_tokens,locale)} · ↓ {formatNumber(item.output_tokens,locale)}</small></td><td>{item.first_token_ms==null?'—':`${item.first_token_ms} ms`}</td><td>{item.latency_ms} ms</td><td><span className={`usage-status ${item.status}`}>{t(`usage.${item.status}`)}</span></td></tr>)}</tbody></table>{loading&&<div className="admin-table-state"><span className="action-spinner"/>{t('loading')}</div>}{!loading&&!records.length&&<div className="admin-table-state">{t('usage.empty')}</div>}</div><AdminPagination page={page} pageSize={pageSize} total={total} onPage={setPage} onPageSize={size=>{setPageSize(size);setPage(1)}}/></section>
  </div>
}
