import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { api } from '../api'
import AdminPagination from '../components/AdminPagination'
import Icon from '../components/Icon'
import { formatDate, normalizeLocale } from '../i18n'
import type { AuditLog } from '../types'

export default function AdminAudit() {
  const { t, i18n } = useTranslation(['admin', 'common']); const locale = normalizeLocale(i18n.language)
  const [items, setItems] = useState<AuditLog[]>([]), [query, setQuery] = useState(''), [type, setType] = useState(''), [source, setSource] = useState(''), [outcome, setOutcome] = useState('')
  const [page, setPage] = useState(1), [pageSize, setPageSize] = useState(10), [total, setTotal] = useState(0), [loading, setLoading] = useState(true)
  const [selected, setSelected] = useState<AuditLog | null>(null)
  useEffect(() => { const timer = window.setTimeout(() => { setLoading(true); api.auditLogs({ query, target_type: type, source, outcome, page, page_size: pageSize }).then(value => { setItems(value.items); setTotal(value.total) }).finally(() => setLoading(false)) }, 200); return () => clearTimeout(timer) }, [query, type, source, outcome, page, pageSize])
  const changed = selected && (!!Object.keys(selected.before || {}).length || !!Object.keys(selected.after || {}).length)
  const closeDetail = () => setSelected(null)

  return <div className="admin-content-page"><div className="admin-page-intro"><div><h1>{t('audit.title')}</h1><p>{t('audit.subtitle')}</p></div><span>{t('audit.total', { count: total })}</span></div><section className="admin-list-card"><div className="audit-filters"><label className="admin-search"><Icon name="search" /><input value={query} onChange={event => { setQuery(event.target.value); setPage(1) }} placeholder={t('audit.search')} /></label><select value={type} onChange={event => { setType(event.target.value); setPage(1) }}><option value="">{t('audit.allTypes')}</option>{['user', 'recording', 'resource', 'organization', 'member', 'invitation', 'ai_settings', 'ai_model', 'storage'].map(value => <option value={value} key={value}>{t(`audit.types.${value}`, { defaultValue: value })}</option>)}</select><select value={source} onChange={event => { setSource(event.target.value); setPage(1) }}><option value="">{t('audit.allSources')}</option>{['web','extension','admin','system'].map(value => <option key={value} value={value}>{t(`audit.sources.${value}`)}</option>)}</select><select value={outcome} onChange={event => { setOutcome(event.target.value); setPage(1) }}><option value="">{t('audit.allOutcomes')}</option>{['success','failed','blocked'].map(value => <option key={value} value={value}>{t(`audit.outcomes.${value}`)}</option>)}</select></div>
    <div className="audit-table-wrap"><table className="audit-table"><thead><tr><th>{t('audit.columns.action')}</th><th>{t('audit.columns.target')}</th><th>{t('audit.columns.actor')}</th><th>{t('audit.columns.context')}</th><th>{t('audit.columns.origin')}</th><th>{t('audit.columns.time')}</th><th /></tr></thead><tbody>{items.map(item => <tr key={item.id} className={selected?.id === item.id ? 'selected' : ''} onClick={() => setSelected(item)} tabIndex={0} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') setSelected(item) }}><td><strong>{t(`audit.actions.${item.action}`, { defaultValue: item.action })}</strong><small>{t(`audit.types.${item.target_type}`, { defaultValue: item.target_type })}</small></td><td>{item.target_label || item.target_id || '—'}</td><td><strong>{item.actor_name || item.actor_email || t('audit.system')}</strong><small>{item.actor_email}</small></td><td><strong>{item.organization_name || '—'}</strong><small className={`audit-outcome ${item.outcome}`}>{t(`audit.outcomes.${item.outcome}`, { defaultValue: item.outcome })}</small></td><td><code>{item.ip_address || '—'}</code><small>{t(`audit.sources.${item.source}`, { defaultValue: item.source })}</small></td><td><time>{formatDate(item.created_at, locale)}</time></td><td className="audit-row-open"><Icon name="chevronRight" /></td></tr>)}</tbody></table>{loading && <div className="admin-table-state"><span className="action-spinner" />{t('loading')}</div>}{!loading && !items.length && <div className="admin-table-state">{t('audit.empty')}</div>}</div>
    <AdminPagination page={page} pageSize={pageSize} total={total} onPage={setPage} onPageSize={size => { setPageSize(size); setPage(1) }} /></section>
    {selected && <><button className="admin-user-drawer-scrim" aria-label={t('common:actions.close')} onClick={closeDetail} /><aside className="admin-user-drawer audit-detail-drawer" role="dialog" aria-modal="true" aria-labelledby="audit-detail-title"><header className="admin-user-drawer-header"><div className="audit-detail-identity"><span><Icon name="clock" size={22} /></span><div><h2 id="audit-detail-title">{t(`audit.actions.${selected.action}`, { defaultValue: selected.action })}</h2><p>{selected.target_label || selected.target_id || t('audit.system')}</p><div className="admin-user-meta"><em>{t(`audit.types.${selected.target_type}`, { defaultValue: selected.target_type })}</em><small className={`audit-outcome ${selected.outcome}`}>{t(`audit.outcomes.${selected.outcome}`, { defaultValue: selected.outcome })}</small></div></div></div><button className="admin-user-drawer-close" aria-label={t('common:actions.close')} onClick={closeDetail}>×</button></header><div className="admin-user-drawer-body audit-detail-body">
      <section className="admin-user-section"><div className="admin-user-section-title"><span><Icon name="list" /></span><div><h3>{t('audit.details.summary')}</h3><p>{t('audit.details.summaryHint')}</p></div></div><div className="audit-detail-grid detail-card-scroll"><div><small>{t('audit.details.target')}</small><strong>{selected.target_label || '—'}</strong></div><div><small>{t('audit.details.targetId')}</small><code>{selected.target_id || '—'}</code></div><div><small>{t('audit.details.actor')}</small><strong>{selected.actor_name || selected.actor_email || t('audit.system')}</strong><span>{selected.actor_email}</span></div><div><small>{t('audit.details.organization')}</small><strong>{selected.organization_name || '—'}</strong></div><div><small>{t('audit.details.source')}</small><strong>{t(`audit.sources.${selected.source}`, { defaultValue: selected.source })}</strong></div><div><small>{t('audit.details.result')}</small><strong>{t(`audit.outcomes.${selected.outcome}`, { defaultValue: selected.outcome })}</strong></div><div><small>{t('audit.details.ip')}</small><code>{selected.ip_address || '—'}</code></div><div><small>{t('audit.details.time')}</small><strong>{formatDate(selected.created_at, locale)}</strong></div></div></section>
      <section className="admin-user-section"><div className="admin-user-section-title"><span><Icon name="device" /></span><div><h3>{t('audit.client')}</h3><p>{t('audit.details.clientHint')}</p></div></div><div className="audit-client-detail detail-card-scroll"><pre>{selected.user_agent || '—'}</pre></div></section>
      <section className="admin-user-section"><div className="admin-user-section-title"><span><Icon name="edit" /></span><div><h3>{t('audit.details.changes')}</h3><p>{t('audit.details.changesHint')}</p></div></div>{changed ? <div className="audit-detail-changes detail-card-scroll"><article><b>{t('audit.before')}</b><pre>{JSON.stringify(selected.before, null, 2)}</pre></article><article><b>{t('audit.after')}</b><pre>{JSON.stringify(selected.after, null, 2)}</pre></article></div> : <div className="audit-no-changes">{t('audit.details.noChanges')}</div>}</section>
    </div></aside></>}
  </div>
}
