import { useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { api } from '../../api'
import { formatDate, formatNumber, normalizeLocale } from '../../i18n'
import type { AdminOrganization, AdminShare, AdminUser } from '../../types'
import AdminPagination from '../AdminPagination'
import Icon from '../Icon'

export default function AdminShareManagement({ owners, organizations }: { owners: AdminUser[]; organizations: AdminOrganization[] }) {
  const { t, i18n } = useTranslation(['admin', 'common']); const locale = normalizeLocale(i18n.language)
  const [searchParams,setSearchParams] = useSearchParams(), selected = searchParams.get('selected') || ''
  const [items, setItems] = useState<AdminShare[]>([]), [query, setQuery] = useState(() => searchParams.get('query') || ''), [status, setStatus] = useState(() => searchParams.get('status') || '')
  const [owner, setOwner] = useState(() => searchParams.get('owner_id') || ''), [organization, setOrganization] = useState(() => searchParams.get('organization_id') || ''), [page, setPage] = useState(() => Math.max(1, Number(searchParams.get('page')) || 1)), [pageSize, setPageSize] = useState(() => Math.max(1, Number(searchParams.get('page_size')) || 10)), [total, setTotal] = useState(0), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const load = () => { setLoading(true); api.adminShares({ query, status, owner_id: owner, organization_id: organization, page, page_size: pageSize }).then(value => { setItems(value.items); setTotal(value.total) }).catch(value => setError(value.message)).finally(() => setLoading(false)) }
  useEffect(() => { const timer = window.setTimeout(load, 180); return () => clearTimeout(timer) }, [query, status, owner, organization, page, pageSize])
  useEffect(()=>{const next=new URLSearchParams({tab:'shares',page:String(page),page_size:String(pageSize)});if(selected)next.set('selected',selected);if(query)next.set('query',query);if(status)next.set('status',status);if(owner)next.set('owner_id',owner);if(organization)next.set('organization_id',organization);setSearchParams(next,{replace:true})},[query,status,owner,organization,page,pageSize,selected,setSearchParams])
  useEffect(() => { if (!loading && selected) document.getElementById(`share-row-${selected}`)?.scrollIntoView({ block: 'center' }) }, [items, loading, selected])
  const reset = (setter: (value: string) => void, value: string) => { setter(value); setPage(1) }
  const detailHref = (item: AdminShare) => {
    const back = new URLSearchParams({ tab: 'shares', selected: item.id, page: String(page), page_size: String(pageSize) })
    if (query) back.set('query', query); if (status) back.set('status', status); if (owner) back.set('owner_id', owner); if (organization) back.set('organization_id', organization)
    return `/admin/resources/${item.resource.id}?tab=shares&item=${item.id}&return_to=${encodeURIComponent(`/admin/resources?${back}`)}`
  }
  return <section className="admin-list-card">
    <div className="resource-filters governance-filters"><label className="admin-search"><Icon name="search"/><input value={query} onChange={event=>reset(setQuery,event.target.value)} placeholder={t('resource.governance.shareSearch')}/></label><select value={organization} onChange={event=>reset(setOrganization,event.target.value)}><option value="">{t('resource.governance.allTeams')}</option>{organizations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={owner} onChange={event=>reset(setOwner,event.target.value)}><option value="">{t('resource.allOwners')}</option>{owners.map(item=><option key={item.id} value={item.id}>{item.name||item.email}</option>)}</select><select value={status} onChange={event=>reset(setStatus,event.target.value)}><option value="">{t('resource.governance.allShareStatuses')}</option>{['active','expired','revoked'].map(key=><option key={key} value={key}>{t(`resource.governance.shareStatus.${key}`)}</option>)}</select></div>
    {error&&<div className="error admin-list-error">{error}</div>}<div className="admin-resource-table-wrap"><table className="admin-resource-table governance-table"><thead><tr><th>{t('resource.governance.link')}</th><th>{t('resource.table.resource')}</th><th>{t('resource.governance.teamOwner')}</th><th>{t('resource.table.views')}</th><th>{t('detail.viewers')}</th><th>{t('resource.governance.security')}</th><th>{t('resource.governance.lastAccess')}</th><th/></tr></thead><tbody>{items.map(item=><tr id={`share-row-${item.id}`} className={selected===item.id?'selected':''} key={item.id}><td><div className="governance-primary"><strong>{item.name||t('resource.governance.unnamedLink')}</strong><small>{formatDate(item.created_at,locale)}</small></div></td><td><Link className="governance-resource-link" to={detailHref(item)}>{item.resource.title}</Link></td><td><div className="resource-owner-cell"><strong>{item.organization?.name||'—'}</strong><small>{item.owner.name||item.owner.email}</small></div></td><td>{formatNumber(item.views,locale)}</td><td>{formatNumber(item.unique_viewers,locale)}</td><td><span className={`governance-badge ${item.status}`}>{t(`resource.governance.shareStatus.${item.status}`)}</span>{item.password_protected&&<small className="inline-security"><Icon name="lock" size={12}/>{t('resource.governance.password')}</small>}</td><td><small>{item.last_accessed_at?formatDate(item.last_accessed_at,locale):'—'}</small></td><td><button className="table-open-action" title={t(item.status==='revoked'?'resource.governance.restore':'resource.governance.revoke')} onClick={async()=>{await api.governAdminShare(item.id,item.status!=='revoked');load()}}><Icon name={item.status==='revoked'?'link':'unlink'}/></button></td></tr>)}</tbody></table>{loading&&<div className="admin-table-state"><span className="action-spinner"/>{t('loading')}</div>}{!loading&&!items.length&&<div className="admin-table-state"><Icon name="share" size={28}/>{t('resource.governance.noShares')}</div>}</div><AdminPagination page={page} pageSize={pageSize} total={total} onPage={setPage} onPageSize={value=>{setPageSize(value);setPage(1)}}/>
  </section>
}
