server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  location /assets/ {
    add_header Access-Control-Allow-Origin "*" always;
    try_files $uri =404;
  }
  location /backend/ {
    proxy_pass http://api:8000/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
  location / { try_files $uri $uri/ /index.html; }
}
